 # NumPy
 
 
 ### Import the numpy package under the name as np

In [3]:
import numpy as np

### Print the numpy version and the configuration

In [2]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
blas_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__info']
    libraries = ['openblas64__info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
openblas64__lapack_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
lapack_ilp64_opt_info:
    library_dirs = ['D:\\a\\numpy\\numpy\\build\\openblas64__lapack_info']
    libraries = ['openblas64__lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBO

### Create a null vector of size 10

In [3]:
z= np.zeros(10)
print(z)
print(type(z))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


### Create a null vector of size 10 but the fifth value which is 1

In [4]:
z= np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49

In [6]:
z= np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
z= np.array([1,2,3,4,5])
print(z)

[1 2 3 4 5]


In [8]:
z=np.array([[1],[2],[3]])
print(z)

[[1]
 [2]
 [3]]


### Create a 3*3 matrix

In [6]:
matrix= np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Matrix slicing

In [7]:
matrix[1,2]

6

In [12]:
matrix[: 2:1]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
matrix[-3:-3:-1]

array([], shape=(0, 3), dtype=int32)

In [14]:
matrix[-3:-1:,-3:-2:]

array([[1],
       [4]])

In [15]:
matrix.shape

(3, 3)

In [16]:
matrix.size

9

### To check dimension of matrix

In [17]:
matrix.ndim

2

### Max and Min values of Matrix

In [18]:
print(np.max(matrix))

9


In [19]:
print(np.min(matrix))

1


### To find max on culumns of matrix

In [20]:
print(np.max(matrix,axis=0))

[7 8 9]


### To find max on rows of matrix

In [21]:
print(np.max(matrix,axis=1))

[3 6 9]


In [22]:
print(np.max(matrix,axis=1)[1])

6


### mean, variance and standard deviation

In [23]:
print(np.mean(matrix))

5.0


In [24]:
print(np.std(matrix))

2.581988897471611


In [25]:
print(np.var(matrix))

6.666666666666667


### Reshaping arrays

In [26]:
print(matrix.reshape(9,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [27]:
print(matrix.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [28]:
print(matrix.flatten())

[1 2 3 4 5 6 7 8 9]


### Transpose of matrix

In [29]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(matrix.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Determinant and rank

In [35]:
print(np.linalg.det(matrix))

0.0


In [34]:
print(np.linalg.matrix_rank(matrix))

2


### Diagonal

In [36]:
print(matrix.diagonal())

[1 5 9]


In [37]:
print(matrix.diagonal(offset=1))

[2 6]


In [38]:
print(matrix.diagonal(offset=2))

[3]


In [39]:
print(matrix.diagonal(offset=-1))

[4 8]


### Trace

In [40]:
matrix.trace?

In [41]:
print(matrix.trace())

15


In [42]:
print(matrix.trace(offset=1))

8


In [43]:
print(matrix.trace(offset=-1))

12


### Dot product

In [44]:
matrix1= np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix1)
print(matrix2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(np.dot(matrix1,matrix2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


### Cross Product

In [46]:
print(matrix1 * matrix2)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [47]:
print(matrix1 + matrix2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [48]:
print(matrix1 - matrix2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [49]:
print(np.add(matrix1,matrix2))

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [51]:
print(np.subtract(matrix1,matrix2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Random Values

In [53]:
print(np.random.randint(0,11,5))

[ 4  5 10  8  7]


In [54]:
print(np.random.randint(0,11,9))

[ 4  4  4  1  8  8  4 10  0]


In [56]:
print(np.random.randint(0,11,9).reshape(3,3))

[[ 4  6  5]
 [ 3  8  8]
 [10 10  0]]


In [57]:
print(np.random.normal(1.0,2.0,10).reshape(2,5))

[[-0.20499416  2.17203662  0.0657836   1.64141407  0.0811575 ]
 [-0.13601803  3.61287364 -0.52647074  1.03349652  4.15306714]]
