Import NumPy

In [1]:
import numpy as np

Print the numpy version

In [2]:
print(np.__version__)

1.23.5


Create a null vector of size 10

In [5]:
z=np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth which is 1

In [6]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector ranging from 10 to 49

In [9]:
z=np.arange(10,50).reshape(10,4)
print(z)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]


Reverse a vector

In [10]:
z=np.arange(50)
print(z[: :-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 3*3 matrix with value from 0 to 8

In [11]:
z=np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find index of non zero elements from [1,2,0,0,4,0]

In [12]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


Create a 3*3 identity matrix

In [13]:
nz=np.eye(3)
print(nz)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3*3 array with random values

In [16]:
r=np.random.randint(0,100,9).reshape(3,3)
print(r)

[[68 79 87]
 [22 36 56]
 [13 43 37]]


Create a 10*10 array with random values and find min and max

In [23]:
np.random.seed(5)

r=np.random.randint(0,1000,100).reshape(10,10)
print(r)
print(r.max())
print(r.min())

[[867 206 701 998 118 400  73   8 740 743]
 [958 411 624 670 720 519 204 911 113 437]
 [999  80  27  44 205 715  65 431 542 980]
 [ 86 637 146 254 377 649 362  41 446 897]
 [210 103 144 974   5 826 768 976 900 110]
 [676 873 691 539 799 770 324 294 105 979]
 [147 274 881 245 135 868 364 621 670 190]
 [779 491 835 380 449 183 387 603  78 923]
 [925 801 729 853 391 528  94  14 986 799]
 [265 550 815 144 389 418 685 699 408 397]]
999
5


Create a random vector of size 30 and find mean

In [24]:
r=np.random.randint(0,100,30).reshape(10,3)
print(r)
print(r.mean())

[[31 32 76]
 [44  5 14]
 [47 94 82]
 [ 0  7 86]
 [16 64  8]
 [90 44 37]
 [94 75  5]
 [22 52 69]
 [82 60 91]
 [29 88 97]]
51.36666666666667


Create a 2d array with 1 on the border and 0 inside

In [25]:
z=np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Create a 5*5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
z=np.diag(1+np.arange(4),k=-1)
print(z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Create 8*8 matrix and fill it with a checkerboard pattern

In [41]:
z=np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


Create a checkerboard 8*8 matrix using the tile function

In [50]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Normalize a 5*5 random matrix

In [52]:
z=np.random.random((5,5))
print(z)
r=z.max()
print(r)
s=z.min()
print(s)
z=(z-s)/(s-r)
print(z)

[[0.44660783 0.80047642 0.02039138 0.57261865 0.41138362]
 [0.9851368  0.80140153 0.0539621  0.19047777 0.45241885]
 [0.70294208 0.33204815 0.3599832  0.92147057 0.95363051]
 [0.40768573 0.89857115 0.33025325 0.08273857 0.52671757]
 [0.66084439 0.89298429 0.96515755 0.76993268 0.75909912]]
0.9851367976958045
0.020391378448150643
[[-0.44179163 -0.8085916  -0.         -0.57240725 -0.40528022]
 [-1.         -0.80955052 -0.03479749 -0.17630184 -0.447815  ]
 [-0.70749307 -0.32304561 -0.35200148 -0.93400722 -0.96734238]
 [-0.4014472  -0.910271   -0.32118512 -0.06462554 -0.52482881]
 [-0.66385701 -0.90447998 -0.97929065 -0.7769317  -0.76570225]]


Create a custom dtype that describe a color as four unsigned bytes (RGBA)

In [53]:
color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
color

C:\Users\asus\AppData\Local\Temp\ipykernel_11956\3952796063.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

Multiply a 5 * 3 matrix by a 3 * 2 matrix

In [55]:
z1=np.dot(np.ones((5,3)),np.ones((3,2)))
print(z1)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


How to round away from zero a float array

In [59]:
z=np.random.uniform(-10,+10,10)
print(z)
print(np.trunc(z+np.copysign(0.5,z)))

[ 3.18834561  9.73002883 -7.85020933  1.61837055 -0.5434369   3.04541572
 -5.16281892 -9.37739873  0.88464705 -2.70579642]
[ 3. 10. -8.  2. -1.  3. -5. -9.  1. -3.]


Extract the integer part of a random array using 5 different methods.

In [60]:
z=np.random.uniform(0,10,10)
print(z)
print(z-z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[8.92333275 4.59345595 4.186541   6.32905541 5.27178833 9.6121114
 7.89010115 4.96695509 2.11141001 6.03984141]
[8. 4. 4. 6. 5. 9. 7. 4. 2. 6.]
[8. 4. 4. 6. 5. 9. 7. 4. 2. 6.]
[8. 4. 4. 6. 5. 9. 7. 4. 2. 6.]
[8 4 4 6 5 9 7 4 2 6]
[8. 4. 4. 6. 5. 9. 7. 4. 2. 6.]


Create a 5 * 5 matrix with row values ranging from 0 to 4

In [61]:
z=np.zeros((5,5))
z+=np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Cosider a generator function that generate 10 integers and use it to build an array

In [64]:
def generate():
    for x in range(10):
        yield x

z=np.fromiter(generate(),dtype=float,count=-1)
print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


Create a random vector of size 10 and sort it.

In [70]:
z=np.random.randint(1,100,10)
print(z)
z.sort()
print(z)

[62 85 53 75 26 10 32 40 60 23]
[10 23 26 32 40 53 60 62 75 85]


How to sum a small array faster than np.sum

In [74]:
z=np.arange(1,100,10)
print(z)
a=np.add.reduce(z)
print(a)

[ 1 11 21 31 41 51 61 71 81 91]
460


Cosider two random array A and B, check if they are equal

In [78]:
z1=np.random.randint(1,5,5)
z2=np.random.randint(1,5,5)
print(z1,"\n",z2)
equal=np.allclose(z1,z2)
print(equal)

[1 2 2 1 4] 
 [3 3 3 3 4]
False


Make an array immutable

In [81]:
z=np.zeros(10)
z.flags.writeable=False
z[0]=1

ValueError: assignment destination is read-only

Consider a random 10 * 2 matrix representing cartesian coordinates, convert them to polar coordinates

In [86]:
z=np.random.randint(1,100,20).reshape(10,2)
print(z)
x,y=z[:,0],z[:,1]
print(x)
print(y)
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[[74 70]
 [78 34]
 [65  4]
 [95 46]
 [71 59]
 [53 68]
 [12 66]
 [22  9]
 [32 48]
 [78 79]]
[74 78 65 95 71 53 12 22 32 78]
[70 34  4 46 59 68 66  9 48 79]
[101.86265263  85.08818954  65.12296062 105.55093557  92.31467922
  86.21484791  67.08203932  23.76972865  57.68882041 111.01801656]
[0.75762753 0.41106455 0.06146096 0.45093643 0.69335131 0.90873586
 1.39094283 0.38831872 0.98279372 0.7917675 ]


Create random vector of size 10 and replace the maximum value by 0

In [90]:
z=np.random.randint(1,100,10)
print(z)
z[z.argmax()]=0
print(z)

[50 70 42 77 80 39 80 82 39 44]
[50 70 42 77 80 39 80  0 39 44]


Given two arrays, x and y, construct the cauchy matrix C(Cij = 1/(xi-yj))

In [91]:
x=np.arange(8)
y=x+0.5
print(x,"\n",y)
c=1.0 / np.subtract.outer(x,y)
print(c)
print(np.linalg.det(c))

[0 1 2 3 4 5 6 7] 
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
3638.1636371179666


How to convert a float(32 bits) array into an integer(32 bits) in place?


In [95]:
z=np.arange(10,dtype=np.int32)
print(z)
z=z.astype(np.float32,copy=False)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
